### PR TITLE
Fix missing home folder icon

### PR DESCRIPTION
**Pull request by germanfr**
Using [freedesktop specification](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names) standard icon name.

### CODE REVIEW

**Comment by NikoKrause** [comment]
Is the home folder icon missing for you?
Which icon theme do you use?

**Comment by germanfr** [comment]
Adwaita. The `folder-home` name is no longer used, it's not in the spec. Most of the themes I have doesn't have that icon.

Also missing software manager's icon, but that's because I'm on Manjaro and I don't have mintinstall.

**Comment by NikoKrause** [comment]
Ah. I'll change it then.

Yeah. You can change that button in Custom Launcher settings. I don't know, but every OS is using different Software Centers, right? Ubuntu, Arch, Manjaro. I don't think there is a way, to make it work on every OS?

**Comment by germanfr** [comment]
Yeah it's impossible. But this little fix is cross platform for sure.

**Comment by cinnamoner** [comment]
@germanfr Now that is an interesting aspect. Never thought about installing Stark in Manjaro Cinnamon. Anyways, please tell me how do you find Manjaro Cinnamon? Has it ever broken? Cause being a rolling distro ... it's (in theory) more prone to breakages. Just curious, cause I had been thinking about making Manjaro Cinnamon my daily driver. Thanks.

**Comment by Odyseus** [comment]
Hello, g@ys.

@NikoKrause: In case that you didn't know, you can add your own icons to your applet and use them by name so you don't have to deal with missing icons nor hard-coded paths to icon files. You just have to create a folder called **icons** in the root of your applet and all icons inside that folder will be *loaded into the icon theme* (I don't know if that is the correct way of expressing that). I was forced to do this when I started to see missing icons due to the use of different icon themes. Furthermore, some actions or concepts are impossible to represent with the icons provided by the icons themes, so one is forced to use a custom icon.

**Comment by germanfr** [comment]
Thanks @Odyseus for pointing that out. In this case it was just a wrong name. For the package manager one could use `system-software-install` or do what you say. The program would still be missing though. Cheers.

**Review by NikoKrause — APPROVED** [review]

**Comment by NikoKrause** [comment]
@germanfr 
I replaced Software Manager (mintinstall) with Printer.
Can you check, if it works on Manjaro and if all icons are there?

**Comment by germanfr** [comment]
Yes the printer icon shows and the program launches.

**Comment by NikoKrause** [comment]
Thanks

**Pull request merged**
